all:
	cd test_SPPwDstbRTT && make all

time: all
	cd test_SPPwDstbRTT && make time

time_chunk_sizes: all
	cd test_SPPwDstbRTT && make time_chunk_sizes

iprofiler: all
	cd test_SPPwDstbRTT && make iprofiler

valgrind: all
	cd test_SPPwDstbRTT && make valgrind

massif: all
	cd test_SPPwDstbRTT && make massif

massif_chunk_sizes: all
	cd test_SPPwDstbRTT && make massif_chunk_sizes

helgrind: all
	cd test_SPPwDstbRTT && make helgrind

test:
	cd test_SPPwDstbRTT && make test

clean:
	cd test_SPPwDstbRTT && make clean

-include $(DEPENDS)
